# Generated by Django 3.1.6 on 2021-03-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dutylist', '0002_duty_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='timestamp',
            new_name='created',
        ),
    ]
